### ISSUE TITLE
Upload modules from previous project

### ISSUE THREAD

**Issue by robperch** [santibatte/dpa_2021#42]
## Tasks
- [x] Upload modules created for class `Intro a CD` in order to recycle code for this project.
- [x] Update issues related to the creation of the processing pipeline
    - [x] Issue objective
    - [x] Modules related and modules objective
