### ISSUE TITLE
Checklist to complete Checkpoint 4

### ISSUE THREAD

**Issue by codeMariana** [santibatte/dpa_2021#93]
- [x] README.md actualizado -> incluye instrucciones de cómo correr tu luigi.
- [x] requirements.txt actualizado.
- [x] Imagen de DAG en verde con las 8 tareas.
- [x] Código.
- [x] En tu carpeta sql debe existir un script create_metadata_tables.sql en donde está el código en sql correspondiente a la creación de las tablas que ocuparás para almacenar la metadata.
